main = ".open-next/worker.js"
name = "browser-worker-presentation"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# R2 bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "hafid-learn-r2-object-storage"

# Environment variables (secrets should be set via `wrangler secret put`)
[vars]
CLOUDFLARE_ACCOUNT_ID = "444d6c9c3590912e495550f91435d901"

